<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mini_servo_firmware</name>
  <version>1.0.0</version>
  <description>Arduino firmware for driving the mini servo arm over an Adafruit PCA9685 PWM board</description>
  <maintainer email="mdicicco@gmail.com">Matt DiCicco</maintainer>
  <license>BSD</license>
  <author email="mdicicco@gmail.com">Matt DiCicco</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
