mini_servo:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - mini_servo_joint_1
      - mini_servo_joint_2
      - mini_servo_joint_3
      - mini_servo_joint_4
      - mini_servo_joint_5
      - mini_servo_joint_6
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: follow_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - mini_servo_joint_1
        - mini_servo_joint_2
        - mini_servo_joint_3
        - mini_servo_joint_4
        - mini_servo_joint_5
        - mini_servo_joint_6
  position_controller:
    type: position_controllers/JointPositionController
    joints:
      - mini_servo_joint_1
      - mini_servo_joint_2
      - mini_servo_joint_3
      - mini_servo_joint_4
      - mini_servo_joint_5
      - mini_servo_joint_6
    gains:
      mini_servo_joint_1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      mini_servo_joint_2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      mini_servo_joint_3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      mini_servo_joint_4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      mini_servo_joint_5:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      mini_servo_joint_6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1